debug: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./samples # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password: 123456 # database 密碼
    platform: h2
    
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect